### ISSUE TITLE
Export support for glTF seperated (gltf, bin, textures)

### ISSUE THREAD

**Issue by Blitzy** [donmccurdy/glTF-Report-Feedback#11]
It'd be great to be able to export glTF files out of the tool as a zip archive of a seperated glTF.
Separated glTF files are great for large scale projects that have a lot of common textures used across many different models. The browser only has to download the common texture once and later requests for it can be retrieved from the cache.

Right now I can re-seperate the exported glb using another tool, but its just an extra step in the pipeline that could be an option or checkbox of gltf.report export.

**Comment by donmccurdy** [comment]
I'd meant to get around to this, but it slipped before launching the site. Done! There's now an export option for .gltf (in an uncompressed ZIP archive).

![Screen Shot 2021-07-19 at 12 51 48 PM](https://user-images.githubusercontent.com/1848368/126219360-3cbc0811-4a66-43af-a91a-c5d44052c856.png)
