### ISSUE TITLE
What light/shadow/env map setup does the viewer use?

### ISSUE THREAD

**Issue by natarius** [donmccurdy/glTF-Report-Feedback#13]
> NOTICE: For questions about writing scripts with the glTF-Transform API, I recommend opening a discussion at https://github.com/donmccurdy/glTF-Transform/discussions instead — For all other questions, please carry on. 🙂

**Comment by donmccurdy** [comment]
Hi @natarius! This viewer is using three.js-based `<model-viewer/>` as the viewer component.  Its default 'neutral' lighting setup is described here, and there should be code in the project's repository as well:

https://modelviewer.dev/examples/lightingandenv/#neutralLighting

The other available IBLs are commonly found on various HDRI library websites, like https://polyhaven.com/hdris.
