### ISSUE TITLE
Configure PWA

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Report-Feedback#14]
Would be great if this site worked offline. See report on https://www.pwabuilder.com/.

**Comment by marwie** [comment]
Would love to have this as a PWA too - would be happy to create a PR / help with that if necessary

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/provide-a-progressive-web-app-pwa.
