### ISSUE TITLE
Enable camera navigation/panning

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Report-Feedback#17]
**Is your feature request related to a problem? Please describe.**
Since this is mostly an analysis tool, it would be great if the camera had a few more degrees of movement.
Right now, loading in e.g. architectural or photogrammetry models and trying to navigate them is hard (can only rotate around the center).

**Describe the solution you'd like**
Easiest would probably be to use the panning sample from https://modelviewer.dev/examples/stagingandcameras/#panning or https://modelviewer.dev/examples/annotations/index.html#cameraViews

**Comment by donmccurdy** [comment]
Merging to https://github.com/donmccurdy/glTF-Report-Feedback/issues/10.

**Comment by donmccurdy** [comment]
Added in latest release —
![Screenshot 2022-11-13 at 11 54 16 PM](https://user-images.githubusercontent.com/1848368/201578340-03d48f58-c755-46b9-8047-f2fef947c546.png)
