### ISSUE TITLE
Support EXT_mesh_gpu_instancing

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Report-Feedback#18]
**Is your feature request related to a problem? Please describe.**
The gltf-transform instance command can generate files that use EXT_mesh_gpu_instancing, but the resulting files can't be viewed in gltf.report. I assume this is because threejs' GltfLoader and in turn model-viewer don't support this yet; wanted to bring it up here as feature request anyways :)
Seems you're already in this discussion: https://github.com/mrdoob/three.js/issues/21937

**Describe alternatives you've considered**
Created files can alternatively viewed with https://sandbox.babylonjs.com/ in the meantime.

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/support-extmeshgpuinstancing.
