### ISSUE TITLE
Use virtual scrolling for validation errors

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Report-Feedback#19]
For some assets (see https://github.com/donmccurdy/glTF-Transform/issues/489) the list of errors can be very long, and/or crash the tab because there are too many DOM nodes. It would be best to try to collapse similar errors, and/or set up virtual scrolling.

**Comment by lexaknyazev** [comment]
Does the website decode `EXT_meshopt_compression` internally before running the validator?

**Comment by donmccurdy** [comment]
Ideally it probably wouldn't, but currently yes. 👍

**Comment by lexaknyazev** [comment]
> re-serialized (possibly with edits made in the script tab) when the validation tab opens

This should probably be up to the user. Consider these events:
1. A compressed asset is loaded. The validator may check whether it's valid as-is (even with unsupported extensions).
2. The compression is decoded. I'm not sure about how error handling is implemented there. What if the compressed bitstream was invalid?
3. The asset is re-serialized. At this stage, the new asset may contain issues accidentally introduced by glTF-Transform as well as pre-existing data issues that were hidden inside the compressed bitstream.

> collapse similar errors

The most intuitive UX would probably be to always group issues that have identical `pointer` and `code` properties.

**Comment by donmccurdy** [comment]
Validation errors are now paginated — tracking the issue of pre-ingestion validation in https://github.com/donmccurdy/glTF-Report-Feedback/issues/35.
