### ISSUE TITLE
Animation playback and controls

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Report-Feedback#2]
Currently models are displayed statically, animation is not played. Viewer should be enhanced to play one or more chosen animations, or to adjust morph targets.

**Comment by Radlad-io** [comment]
Bump. This is an incredibly helpful tool but I'm having a little trouble using it currently because I'm working on a model that animates in.

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/animation-playback.
