### ISSUE TITLE
Viewport shading modes

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Report-Feedback#20]
Would be helpful to provide a few different rendering views, similar to Blender or Sketchfab. Mostly for debugging rather than modeling in this case. Consider:

- Wireframe
- Solid
- Lookdev
- Texel Density
    - https://www.artstation.com/artwork/GaLAgN
    - https://www.artstation.com/artwork/8eJY0G
- Overdraw
- Channel (BaseColor, O/R/M, Normal, ...)

**Comment by DennisSmolek** [comment]
<img width="1446" alt="Screen Shot 2022-04-06 at 18 12 35" src="https://user-images.githubusercontent.com/1397052/162088298-a30aceda-2d48-473d-8525-7998c648ca63.png">
<img width="1454" alt="Screen Shot 2022-04-06 at 18 12 55" src="https://user-images.githubusercontent.com/1397052/162088308-36d00247-3f96-4d56-879d-be92cdfb51cc.png">

Something else I'd like to advocate for is either the Matcap view (like sketchfab) or the `scene.overrideMaterial`

Working on something we plan on handling mostly in three meant the model was totally blown out.
Adjusting the ambient light only made it a greyscale. 

Luckily the EnvMap option was there to at least see the windows.

having a matcap or some generic override would cover a lot of these cases..

Also maybe a toggle for a directional or some kind of shadow casting light..

**Comment by donmccurdy** [comment]
Is a "Matcap view" basically equivalent to Blender's "Solid" view (which i think has some choices of Matcap) or is there some other difference I'm missing?

![Screen Shot 2022-04-06 at 8 35 01 PM](https://user-images.githubusercontent.com/1848368/162097217-86e330af-738b-4a3a-a698-024fdfb82e27.png)

**Comment by DennisSmolek** [comment]
I'm loosing my mind... I swear I replied to this with a picture and stuff, I apologize for the delay.

Anyway yes, they use a slightly metallic (boring) matcap.

They occasionally have the normals or what they refer to as "surface" as an additional option..

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/viewport-shading-modes.
