### ISSUE TITLE
Can't type in command editor on mobile

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Report-Feedback#26]
**Describe the bug**
When switching to desktop layout on a mobile phone, commands can be run. However, typing is hard to impossible - seems selection, typing, backspace all only work sporadically (didn't find a clear pattern).

Running the default command on mobile seems to work fine though.

**Smartphone (please complete the following information):**
 - Device: Mi 9
 - OS: Android
 - Browser: Chrome
 - Version: 100.0

**Additional context**
I understand running commands on Android might not be a priority 😅

**Comment by donmccurdy** [comment]
>  desktop layout on a mobile phone

What does this mean? Landscape orientation, or the 'request desktop site' button? My intention (see reply in #25) was to disable most non-viewer features in mobile devices, the code editor especially is much harder to support there.

**Comment by hybridherbst** [comment]
Yes, I'm referring to "request desktop layout". Functionally, things seem to work fine (can run commands, can view textures, see errors, etc).

From my perspective code editing on mobile without any fancy features (just a regular text input, highlighting would be nice but not necessary) would totally work.

For context, was just trying to quickly turn a model to unlit on the go.

**Comment by donmccurdy** [comment]
I'd like to improve the mobile experience, but I think supporting the script editor in that context is more than I want to manage. Going to close this one as "won't fix". That said, exposing other ways (e.g. UI) to convert materials to unlit would probably be a good improvement for both desktop and mobile.
