### ISSUE TITLE
Distinguish between normalized and unnormalized attributes

### ISSUE THREAD

**Issue by zeux** [donmccurdy/glTF-Report-Feedback#27]
Right now the Inspect view shows the type of encoding for each vertex stream, eg "uint16", but that display doesn't differentiate between whether a stream is normalized or not.

This isn't a problem for some streams that always are normalized (like normals) or never are (like joint indices), but is more ambiguous for positions/texture coordinates that can be normalized or not when KHR_mesh_quantization is used.

It would be neat to specify a more precise type, perhaps borrowing a page from HLSL/et al and saying "snormN"/"unormN" for normalized integer streams and "intN"/"uintN" for unnormalized integer streams.

**Comment by donmccurdy** [comment]
Thanks @zeux! I'm implementing this in https://github.com/donmccurdy/glTF-Transform/pull/638, which should be available via CLI as `gltf-transform inspect input.glb` soon. It will take me a bit longer to update gltf.report to the latest version of gltf-transform, and to get a new website release out.

**Comment by donmccurdy** [comment]
Pushed in latest release!
