### ISSUE TITLE
Does Meshopt Compression Run Simplification?

### ISSUE THREAD

**Issue by stevenpaulhoward** [donmccurdy/glTF-Report-Feedback#28]
Hey! First and foremost, thank you for sharing this beautiful tool you have built.

I'm curious if the Meshopt -cc export function utilizes simplification? I haven't seen any lossyness in my models when leveraging meshopt through the gltf.report exporter. I'm also assuming it doesn't because I see vertex count always stays the same when comparing my original file to the meshopt compressed file. But just want to double check this is the right assumption and get clarification on whether you're implementing Simplification as well (and if so, whether you're using meshopt_simplify or meshopt_simplifySloppy)

Thanks so much again!

**Comment by donmccurdy** [comment]
Hi @stevenpaulhoward, and thanks! This export option only does compression — no structural or topological changes. It quantizes geometry to lower precision then runs the meshopt encoders to compress that bitstream (using the glTF extension EXT_meshopt_compression). 

By comparison — the [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf) tool does a lot more than just compression — simplifying, merging meshes, and flattening the scene graph, all adding up to a thorough overhaul of the input file.

I'd like to support simplification separately (see https://github.com/donmccurdy/glTF-Transform/issues/244), and the meshoptimizer library has just recently exposed its simplification algorithm, so I might use that. But so far, that isn't integrated here.

**Comment by donmccurdy** [comment]
Simplification has since been added in glTF-Transform, though I haven't pulled in the updates to https://gltf.report yet.
