### ISSUE TITLE
Custom zipped GLTF won't open

### ISSUE THREAD

**Issue by pepefeliblu** [donmccurdy/glTF-Report-Feedback#29]
I am trying to create a custom GLTF zipped file, which would be a folder containing all the needed assets, bin and gltf file. 

For this purpose I am using Nodejs and [JSZip](https://stuk.github.io/jszip/) library. 

Unfortunately, when I'm trying to drop the zip file into [gltf.report](https://gltf.report/) I get the following error:

"Cannot read properties of undefined (reading 'buffer')"

I cannot understand where my error would be, as I am able to extract the contents using my local computer and all files seem correct.

**Comment by donmccurdy** [comment]
Hi! I'll need a way to reproduce this in order to help. Can you share the ZIP here? What browser and operating system are you using?
