### ISSUE TITLE
Total vertex count of all meshes

### ISSUE THREAD

**Issue by pkirsten** [donmccurdy/glTF-Report-Feedback#31]
I often quickly inspect different glb files with your tool and compare basic infos like count of meshes, texture size, size on GPU, draws etc. for further optimization.

The vertex count is shown per mesh in the inspector, but a total of all vertices would be interesting for a quick look either in the inspector or in the history stats window.

![image](https://user-images.githubusercontent.com/38910969/189752485-ddfc7710-8cd0-4b37-ac93-e9a3bfd7af96.png)

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/improved-summary-statistics.
