### ISSUE TITLE
Orbit Controls - Enable panning

### ISSUE THREAD

**Issue by tomorrowevening** [donmccurdy/glTF-Report-Feedback#33]
Rotate + zoom are currently enabled, it would be very helpful if we can pan too

**Comment by donmccurdy** [comment]
Agreed! This is planned for the next update, but I'm not sure when I'll get that published yet.

**Comment by donmccurdy** [comment]
Added in latest release —
![Screenshot 2022-11-13 at 11 54 16 PM](https://user-images.githubusercontent.com/1848368/201578255-1944f684-245b-4daf-94e2-2134e9d13e7a.png)
