### ISSUE TITLE
Error loading glTF with KTX2 textures

### ISSUE THREAD

**Issue by echadwick-wayfair** [donmccurdy/glTF-Report-Feedback#34]
**Describe the bug**
Error loading glTF with KTX2 textures

```
gltf.report says
Unexpected render error: Cannot set properties of null (setting 'encoding')
OK

```
**To Reproduce**
1. Download a glTF with KTX2 textures. For example: https://github.com/KhronosGroup/3D-Formats-Guidelines/tree/main/samples/Duck/glTF-KTX-ETC1S
4. Go to https://gltf.report/
5. Drag and drop the glTF
6. See error

**Expected behavior**
glTF with KTX2 textures should load in glTF Report; it used to work last time I checked which was a couple months ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/40177036/198660842-750e2cef-4eaf-44a7-9923-0c676eb1f349.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.62 (Official Build) (64-bit)

**Comment by donmccurdy** [comment]
This is working for me —

![Screenshot 2022-11-04 at 3 30 50 PM](https://user-images.githubusercontent.com/1848368/200059799-04d475f4-a4f8-4203-9821-611430ef6bbb.png)

I'm using a CDN to host the KTX2 and Draco decoders, I think there may have been a temporary slowdown or outage on that host...

**Comment by echadwick-wayfair** [comment]
Thanks Don, it;s working now.
