### ISSUE TITLE
Textures with transparency are sometimes hard / impossible to read

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Report-Feedback#40]
**Is your feature request related to a problem? Please describe.**
I have a glb containing transparent UI graphics. Often times those graphics are white / have fine images and a transparent background. In my current case it's not possible to see much of that image:

![image](https://user-images.githubusercontent.com/5083203/206310097-8093d923-6371-4c6a-b538-e50def629c02.png)

**Describe the solution you'd like**
Either change the default background color of the images to a slightly darker grey tone or maybe a way to toggle the background.
Below is a quick test with a medium grey:

![image](https://user-images.githubusercontent.com/5083203/206310260-cc3107e2-38c0-43e5-99d2-d049563883db.png)

**Additional context**
[scene.zip](https://github.com/donmccurdy/glTF-Report-Feedback/files/10180520/scene.zip)

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/improve-visibility-of-transparent-textures.
