### ISSUE TITLE
File names with dot characters are not handled well 

### ISSUE THREAD

**Issue by looeee** [donmccurdy/glTF-Report-Feedback#41]
**Describe the bug**

Given a folder structure that looks like this:

```
tank_tanker_V0.2.gltf
tank_tanker_V0.2.bin
tex_tank_default_concrete_n.png
... // additional textures
```

When I upload these to gltf.report and then export in binary format, this gets changed to `tank_tanker_V02-v1.glb`. 

More problematic is that when I export in JSON format, I get:

```
tank_tanker_V02.gltf
tank_tanker_V0.2.bin
... // textures unchanged
```

This is quite confusing if your morning coffee hasn't kicked in and you don't see the missing `.`!

If I add even more dots so that I have:

```
tank_tanker_V0.2.1.1.1.1.gltf
tank_tanker_V0.2.bin
```

Then I can no longer export at all and I get the error message:

> Provide file name, without any extension. Name must contain only alphanumeric, underscore, and dash characters.

So it seems this is not a bug? Are dot characters disallowed in glTF file names? 

**To Reproduce**

This occurs with any filename containing dots I think. 

[DamagedHelpetJSONRenamed.zip](https://github.com/donmccurdy/glTF-Report-Feedback/files/10201468/DamagedHelpetJSONRenamed.zip)

**Expected behavior**

Dots should be preserved, as they often provide important version information. 

 - OS:  Windows
 - Browser: Chrome

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/bugs/p/poor-renaming-for-files-with-in-basename.
