### ISSUE TITLE
Error when opening texture view: loading glb containing webp textures?

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Report-Feedback#42]
**Describe the bug**
Dropping a glb containing a webp and a basisu compressed texture. Then clicking the texture view button -> console prints errors and the texture view doesnt open

**To Reproduce**
1. Drop this glb [sceneRoot.zip](https://github.com/donmccurdy/glTF-Report-Feedback/files/10207141/sceneRoot.zip)
2. Click texture view button

**Expected behavior**

Texture View opens and shows previews

**Screenshots**

![20221212-114255_glTF_Report_-_Google_Chrome-needle](https://user-images.githubusercontent.com/5083203/207026420-0e7045e6-926b-4ef4-9c3e-7590776176e7.png)

![image](https://user-images.githubusercontent.com/5083203/207026356-6693578a-3ae8-4ea1-a4da-366278f19131.png)

https://user-images.githubusercontent.com/5083203/207026732-27335c6e-7d19-467a-a642-1259239be190.mp4

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 108.0.5359.99

**Comment by donmccurdy** [comment]
Thanks @marwie! The problem appears to have been the OpenEXR texture in this file, and glTF Report won't be able to show previews or stats about those, but all the same it shouldn't be crashing. Should be fixed on latest release. :)

**Comment by marwie** [comment]
What I should've mentioned is that I usually drop glbs that contain an EXR which never used to crash - only the glb also containing the webp caused it to crash. 

I'm not sure if you already fixed it but when I drop e.g. our scrollytelling sample glb it works fine :)

[madeWithNeedle.zip](https://github.com/donmccurdy/glTF-Report-Feedback/files/10253570/madeWithNeedle.zip)

![image](https://user-images.githubusercontent.com/5083203/208292636-05480e5d-a15e-44b2-a9c3-ddc5b0d8efd4.png)
