### ISSUE TITLE
Gltf Breakdown overview

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Report-Feedback#45]
**Is your feature request related to a problem? Please describe.**
I often use gltf report to review textures inside glbs. What im missing is an overview of the size of the different elements in total (e.g. animations, meshes, textures, json)

**Describe the solution you'd like**
Below of a screenshot of a tool we built internally (installed as a PWA) for that - it would be nice to have an overview in a similar fashion in gltf.report
![image](https://user-images.githubusercontent.com/5083203/212491924-2cc1dcab-c3c6-4fc0-abec-bbfcf65b0c44.png)

Maybe at the top you could add a little table and/or next to the different sections for textures, meshes, animations add the sum in KB of all elements. At the moment for larger files it is not really possible to get a good overview over what parts of the file are maybe a problem and might need optimization (e.g. 80% mesh data)

![image](https://user-images.githubusercontent.com/5083203/212491982-c3ec7ab2-d911-4f85-9172-695ec9fc340d.png)

**Comment by donmccurdy** [comment]
Thanks @marwie! I do like the idea of providing a better overview, perhaps as a "total" row under existing tables, or a summary chart or table at the top.

I'm hesitant to include the JSON size, at this point. Or at least I haven't figured out the right design for that. Related to #35, ideally I don't want to serialize the file every time a change is made (e.g. in the script tab), which would be necessary for an accurate JSON size. The current file size estimates use some heuristics to estimate the JSON size, but it isn't such a good estimate that I'd want to quote the JSON size in isolation.

**Comment by marwie** [comment]
I would be in favor of an overview at the beginning because it's what I usually look at first and only then dive into the specifics (but it might depend on the usecase / focus. That being said: there's quite some whitespace left next to the existing Overview for filling with useful info 😅 

![20230120-220543_212491982-c3ec7ab2-d911-4f85-9172-695ec9fc340d png](https://user-images.githubusercontent.com/5083203/213805145-384188b8-8aed-4fdd-93ed-e15da8aa94f6.png)

About json: how about a button that would update the size / calculate a more accurate size? 
Or: the json size would only happen when the metadata tab becomes visible?

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/improved-summary-statistics.
