### ISSUE TITLE
Multiple glb files at once

### ISSUE THREAD

**Issue by TheCGIMonkey** [donmccurdy/glTF-Report-Feedback#46]
I have multiple glb files that all make up a big assembly - it would be great to beable to open a few files at once to see the files together

An alternative is I could export all the files as a single glb file, but its not ideal.

The glb's could be listed and have the option to hide them

**Comment by donmccurdy** [comment]
Thanks! Transferred to https://gltf-report.canny.io/feature-requests/p/merge-multiple-gltf-documents.
