### ISSUE TITLE
Bulk/Batch export with compression from local folders

### ISSUE THREAD

**Issue by TheCGIMonkey** [donmccurdy/glTF-Report-Feedback#47]
I have 300+ glb files locally, and would like the function to beable to batch compress them all - could be a simple open folder, set compression settings, and hit go, and it opens, and exports one at a time, but without manual input.

Currently, I drag each file one at a time into the website, hit export, and repeat.

**Comment by donmccurdy** [comment]
Hi @TheCGIMonkey! I'd love to see this tool get that powerful some day, but the path from here to there is a pretty long one. In the meantime you might find that glTF Transform (https://gltf-transform.donmccurdy.com/) is a more practical option, it's the library used for processing glTF files here. You can either batch process with scripts written in JavaScript/TypeScript, or use a terminal. On macOS or Linux, a script like this would work:


```bash
npm install --global @gltf-transform/cli
```

```bash
#!/bin/bash

FILES="./path/to/models/*.glb"
for file in $FILES; do
    echo "Compressing $file..."
    gltf-transform draco "${file%.glb}.glb" "${file%.glb}-draco.glb"
done
```
