### ISSUE TITLE
Joints and Inverse Bind Matrices

### ISSUE THREAD

**Issue by EliCDavis** [donmccurdy/glTF-Report-Feedback#50]
**Is your feature request related to a problem? Please describe.**

I've been working on my own GLTF model exporter as an exercise and have struggled with skin-based animations, mainly setting up the joints appropriately.

**Describe the solution you'd like**

I would love a view in which I can visualize the final placement **and orientation** of the joint nodes (and maybe just all nodes?) in the model.
I would also love to be able to view the inverse bind matrices on a per-node bases in a skin view and be able to change it and see the model update in real-time.

**Describe alternatives you've considered**

I've been using blender as a debug tool, but it in itself is inconsistent between object and edit view (when the skin modifier gets applied, which is helpful in its own right). But it doesn't let me modify the inverse bind matrices directly.

**Additional context**

Look into his face and tell me you don't want to help him

![image](https://user-images.githubusercontent.com/9094977/221923609-f95f515f-8f6d-4a8d-b1e1-8bf77e63995c.png)

**Comment by EliCDavis** [comment]
Also, in the end, the blender is just making a best guess for bone pose when translating from the joint concept, which can be misleading.

![image](https://user-images.githubusercontent.com/9094977/222032706-3ada5943-10bc-4d83-8c39-cc7227a77073.png)

**Comment by donmccurdy** [comment]
Hi @EliCDavis! I think a full UI for editing inverse bind matrices is a more niche thing that I can justify building into this tool... You can definitely edit them in the script editor with something like:

```javascript
const skin = document.getRoot().listSkins()[0];
const jointIndex = skin.listJoints().findIndex((joint) => joint.getName() === 'Hip');
const ibm = skin.getInverseBindMatrices();

ibm.setElement(jointIndex, [
  1, 0, 0, 0,
  1, 0, 0, 0,
  1, 0, 0, 0,
]);

```
