### ISSUE TITLE
Data URI texture are not working

### ISSUE THREAD

**Issue by rformato** [donmccurdy/glTF-Report-Feedback#8]
**Describe the bug**
data URI textures fail in gltf file

**To Reproduce**
1. import a gltf file with a data uri texture
2. See the error message `Missing resource: data:image/jpeg;base64,...`

**Expected behavior**
Correctly Import the data uri texture

**Screenshots**
<img width="405" alt="immagine" src="https://user-images.githubusercontent.com/969336/125791928-d83eae41-1554-4945-beb6-078c1c940096.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser Firefox
 - Version 89.0.2

**Comment by donmccurdy** [comment]
Thanks for letting me know! This should be fixed now. 👍
