### ISSUE TITLE
Save scripts to browser local storage/db

### ISSUE THREAD

**Issue by Blitzy** [donmccurdy/glTF-Report-Feedback#9]
While working on asset optimizations, I often want to save the scripts I'm working on inside the browser context.
I have accidentally closed the tab and lost work which is mildly frustrating. I also think it would be very handy to be able to load up saved scripts that are tailored to certain types of optimizations and/or projects: ie (`ProjectA_LowQuality`, `ProjectA_HighQuality`, `ProjectB_Draco-KTX`, etc).

I think a good first pass would be just saving and reloading the script on page load, without having to necessarily have a bunch of UI for saving/loading. This would probably go well with suggestion #6

**Comment by donmccurdy** [comment]
> I have accidentally closed the tab and lost work which is mildly frustrating...

Ahh, I really should have set up an "unsaved changes, are you sure?" warning before the tab closes at least, that's a very quick and easy fix. Will get that in soon at least, sorry about that!

> I also think it would be very handy to be able to load up saved scripts ...

I expect a lot of people are ultimately going to be interested in this, or something like it, so I'm probably going to let this idea sit for a while before and get comments trying any particular solution... localstorage is easy enough but I'm not sure what should happen when multiple tabs are open, I'd like to think about it a bit more.

One idea I had was to connect to the GitHub Gists API, and at least load — possibly save? — scripts that way, but it would require a GitHub login unfortunately.

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/allow-saving-scripts.
